# Generated by Django 5.2.8 on 2025-11-25 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('cv_file', models.FileField(upload_to='uploads/cvs/%Y/%m/', verbose_name='Arquivo CV')),
                ('text_content', models.TextField(blank=True, verbose_name='Conteúdo Extraído')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Pontuação Total')),
                ('summary', models.TextField(verbose_name='Resumo das Qualidades')),
                ('data_json', models.JSONField(default=dict, verbose_name='Dados Detalhados')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Processado em')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(help_text='O que a IA deve procurar exatamente', verbose_name='Descrição')),
                ('weight', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Peso')),
                ('type', models.CharField(choices=[('required', 'Obrigatório'), ('desired', 'Desejável')], default='desired', max_length=10, verbose_name='Tipo')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='recruitment.jobposition')),
            ],
            options={
                'verbose_name': 'Critério',
                'verbose_name_plural': 'Critérios',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobposition'),
        ),
    ]
